name       : haskell-network-uri
version    : 2.6.1.0
release    : 1
source     :
    - http://hackage.haskell.org/package/network-uri-2.6.1.0/network-uri-2.6.1.0.tar.gz : 423e0a2351236f3fcfd24e39cdbc38050ec2910f82245e69ca72a661f7fc47f0
license    : BSD-3-Clause
component  : programming
summary    : This package provides an URI manipulation interface.
description: |
    This package provides an URI manipulation interface.
builddeps  :
    - ghc
    - haskell-parsec
setup      : |
    sudo ghc-pkg recache
    ghc -threaded --make Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --libsubdir="\$compiler/\$pkgid" \
                      --datadir=/usr/share \
                      --sysconfdir=/etc
build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 network-uri-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/network-uri-$version.conf
    rm -f $installdir/usr/lib64/$GHCV/network-uri-$version/*.a
