name       : haskell-network-uri
version    : 2.6.3.0
release    : 6
source     :
    - https://hackage.haskell.org/package/network-uri-2.6.3.0/network-uri-2.6.3.0.tar.gz : a01c1389f15d2cc2e847914737f706133bb11f0c5f8ee89711a36a25b7afa723
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package provides an URI manipulation interface.
description: |
    This package provides an URI manipulation interface.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
