name       : haskell-network-uri
version    : 2.6.1.0
release    : 3
source     :
    - http://hackage.haskell.org/package/network-uri-2.6.1.0/network-uri-2.6.1.0.tar.gz : 423e0a2351236f3fcfd24e39cdbc38050ec2910f82245e69ca72a661f7fc47f0
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package provides an URI manipulation interface.
description: |
    This package provides an URI manipulation interface.
builddeps  :
    - ghc
    - haskell-cabal-install
    - haskell-parsec
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
