name       : haskell-network-uri
version    : 2.6.4.2
release    : 7
source     :
    - https://hackage.haskell.org/package/network-uri-2.6.4.2/network-uri-2.6.4.2.tar.gz : 9c188973126e893250b881f20e8811dca06c223c23402b06f7a1f2e995797228
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package provides an URI manipulation interface.
description: |
    This package provides an URI manipulation interface.
builddeps  :
    - ghc-devel
    - haskell-th-compat-devel
rundeps    :
    - devel :
        - haskell-th-compat-devel
setup      : |
    %haskell_configure
build      : |
    %haskell_build
install    : |
    %haskell_install
    %haskell_register
